package osiyo.xalqaro.osiyo_xu.bot;

import java.util.List;
import java.util.Set;

public interface Science {
    // DENTISTRY 1-semester
    String PRECLINICAL_RESTORATIVE_DENTISTRY = "Preklinik restavratsion stomatologiya";
    String RUSSIAN_LANGUAGE = "Rus tili";
    String BODY_ANATOMY = "Odam anatomiyasi";
    String BIOLOGICAL_AND_PHYSICAL_PHYSICS = "tibbiy va biologik fizilka";
    String BIOLOGY = "Tibbiyotda axborot texnologiyalari";
    String BIOLOGY_TERM = "Lotin tili va tibbiyot terminologiyasi";
    String DENTAL_ENTRY = "Stomatologiyaga kirish";

    // DENTISTRY 2-semester
    String FOREIGN_LANGUAGE_IN_MEDICINE = "Tibbiyotda xorijiy til";
    String PHYSICAL_PHYSICS = "Fiziologiya-yuz-jag' fiziologiyasi";
    String HISTOLOGY_CYTOLOGY_EMBRYOLOGY = "Gistologiya, Sitologiya, Embiriologiya";
    String MEDICINAL_CHEMISTRY = "Tibbiy kimyo";
    String ORTHOPEDIC_DENTISTRY_PROPAEDEUTICS = "ortopedik stomatologiya propedivtikasi";

    // DENTISTRY 3-semester
    String CLINICAL_RESTORATIVE_DENTISTRY = "Klinik restavratsion stomatologiya";
    String HYGIENE_MEDICAL_ECOLOGY = "Gigiyena. Tibbiy ekologiya";

    // DENTISTRY 4-semester
    String BIOCHEMISTRY = "Biokimiyo";
    String MICROBIOLOGY_VIROLOGY_IMMUNOLOGY = "Mikrobiologiya, Virusologiya, Immunologiya";
    String PATHOLOGICAL_ANATOMY = "Patologik anatomiya";
    String PATHOLOGICAL_PHYSIOLOGY = "Patologik fiziologiya";
    String FARMAKOLOGIYA = "Farmakologiya";
    String SECONDARY_DEFORMITIES_AND_PATHOLOGICAL_EROSION = "Ikkilamchi deformatsiyalar va patologik yedirilish";

    // DENTISTRY 5-semester
    String CLINICAL_ANATOMY = "Klenik anatomiya (operativ xirurgiya va topografik anatomiya)";
    String PUBLIC_HEALTH = "Jamoat salomatligai";
    String PROSTHETICS_WITH_NON_REMOVABLE_TEETH = "Olinmaydigan tishlar bilan protezlash";
    String PREVENTION_OF_DENTAL_DISEASES = "Stomatologik kasalliklar profilaktikasi";
    String GNATHOLOGY = "Gnatologiya (Chakka pastki jag' bo'limi kasalliklari)";

    List<String> ONE_SEMESTER_DENTISTRY = List.of(PRECLINICAL_RESTORATIVE_DENTISTRY, RUSSIAN_LANGUAGE, BODY_ANATOMY, BIOLOGICAL_AND_PHYSICAL_PHYSICS, BIOLOGY, BIOLOGY_TERM, DENTAL_ENTRY);
    List<String> TWO_SEMESTER_DENTISTRY = List.of(BODY_ANATOMY, FOREIGN_LANGUAGE_IN_MEDICINE, PHYSICAL_PHYSICS, PRECLINICAL_RESTORATIVE_DENTISTRY, HISTOLOGY_CYTOLOGY_EMBRYOLOGY, MEDICINAL_CHEMISTRY, ORTHOPEDIC_DENTISTRY_PROPAEDEUTICS);
    List<String> THREE_SEMESTER_DENTISTRY = List.of(CLINICAL_RESTORATIVE_DENTISTRY, HISTOLOGY_CYTOLOGY_EMBRYOLOGY, PHYSICAL_PHYSICS, HYGIENE_MEDICAL_ECOLOGY, ORTHOPEDIC_DENTISTRY_PROPAEDEUTICS, BODY_ANATOMY);
    List<String> FOUR_SEMESTER_DENTISTRY = List.of(BIOCHEMISTRY, MICROBIOLOGY_VIROLOGY_IMMUNOLOGY, PATHOLOGICAL_ANATOMY, PATHOLOGICAL_PHYSIOLOGY, FARMAKOLOGIYA, CLINICAL_RESTORATIVE_DENTISTRY, SECONDARY_DEFORMITIES_AND_PATHOLOGICAL_EROSION);
    List<String> FIVE_SEMESTER_DENTISTRY = List.of(CLINICAL_ANATOMY, PATHOLOGICAL_ANATOMY, PATHOLOGICAL_PHYSIOLOGY, FARMAKOLOGIYA, PUBLIC_HEALTH, PROSTHETICS_WITH_NON_REMOVABLE_TEETH, PREVENTION_OF_DENTAL_DISEASES, GNATHOLOGY);

    Set<String> ALL_SCIENCES = Set.of(PRECLINICAL_RESTORATIVE_DENTISTRY, RUSSIAN_LANGUAGE, BODY_ANATOMY, BIOLOGICAL_AND_PHYSICAL_PHYSICS, BIOLOGY, BIOLOGY_TERM, DENTAL_ENTRY,
            FOREIGN_LANGUAGE_IN_MEDICINE, PHYSICAL_PHYSICS, HISTOLOGY_CYTOLOGY_EMBRYOLOGY, MEDICINAL_CHEMISTRY, ORTHOPEDIC_DENTISTRY_PROPAEDEUTICS,
            CLINICAL_RESTORATIVE_DENTISTRY, HYGIENE_MEDICAL_ECOLOGY, BIOCHEMISTRY, MICROBIOLOGY_VIROLOGY_IMMUNOLOGY, PATHOLOGICAL_ANATOMY, PATHOLOGICAL_PHYSIOLOGY, FARMAKOLOGIYA, SECONDARY_DEFORMITIES_AND_PATHOLOGICAL_EROSION,
            CLINICAL_ANATOMY, PUBLIC_HEALTH, PROSTHETICS_WITH_NON_REMOVABLE_TEETH, PREVENTION_OF_DENTAL_DISEASES, GNATHOLOGY);
}
